name: Validate JSON on PR

on:
  push:
  pull_request:

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate JSON
        run: python scripts/validate_json.py
